### ISSUE TITLE
alias

### ISSUE THREAD

**Issue by liamoreilly** [eecs-autograder/autograder-full-stack#20]
Hi,

No bug, but a question that I hope someone can help answer.

We are trying to use javaFX with autograder. The compile command is getting complex so we have tried to use an alias with it.

Specifically, the latter part of our Dockerfile is:
```
# Make JavaFX easy to work with
ENV JAVAFX_PATH=/usr/share/openjfx/lib
RUN echo "alias javafxc='javac --module-path $JAVAFX_PATH --add-modules javafx.controls'" >> /home/autograder/.bashrc
RUN echo "alias javafx='java --module-path $JAVAFX_PATH --add-modules javafx.controls'" >> /home/autograder/.bashrc
# Make autograder user run its bashrc file
ENV BASH_ENV="/home/autograder/.bashrc"
```

Here we setup a .bashrc file to create aliases to the commands "javafxc" and "javafx".
The last line set BASH_ENV which as far as I can tell means that when autograder starts the container, enters as root and then does something like "su autograder" it causes /home/autograder/.bashrc to be sourced. This "should" then mean the aliases are available but when running the compile line of tests javafxc is not found. We have used "env" and "alias" to printout the state and can see the aliases are available correctly. So we have become a bit confused.

Any idea on how to just get these aliases in place such that autograder can execute them?

Thanks,
Liam

**Comment by james-perretta** [comment]
I've never tried using a .bashrc in a docker image, but one way you could
get the same effect is putting the commands into files somewhere on the
PATH. E.g., put a file called javafxc in /usr/local/bin (and add
/usr/local/bin to your PATH), put the command in that file, then mark the
file as executable.

Let me know if that helps!

**Comment by liamoreilly** [comment]
Thanks, that appears to work great. The resulting tail of our Dockerfile is:
```
# Make JavaFX easy to work with
RUN echo '#!/bin/sh' >> /usr/local/bin/javafxc
RUN echo 'javac --module-path /usr/share/openjfx/lib --add-modules javafx.controls $@' >> /usr/local/bin/javafxc
RUN echo '#!/bin/sh' >> /usr/local/bin/javafx
RUN echo 'java --module-path /usr/share/openjfx/lib --add-modules javafx.controls $@' >> /usr/local/bin/javafx
RUN chmod +x /usr/local/bin/javafxc /usr/local/bin/javafx
```
/usr/local/bin is already on that path - so that was handy.
