### ISSUE TITLE
Update nginx to latest version

### ISSUE THREAD

**Issue by james-perretta** [eecs-autograder/autograder-full-stack#21]

**Comment by liamoreilly** [comment]
Hi @james-perretta,

Is there any progress on this please? I have just tried to upgrade our single server production environment from 2021.01.v8 to 21.05.v4 as a first step to go through migrations, with the aim of ending up at 2022.01.v1. However, the images based on nginx:1.13 no longer build as Debian has removed the apt repositories. 

I tried upgrading the dockerfiles to nginx:1.25. This led to npm not being installed. I added npm to apt-get and thought I was making progress. However, then 'website' failed to build with npm failing with a large number of deprecation warnings and an error building npm's deasync package.

Thanks,
Liam

**Comment by james-perretta** [comment]
Hi Liam, Yes, there is, but the branches for it are in a bit of a mess. If you want to try out my current latest branches (which are soon to be merged and released properly, I promise!), try the following branches:
- autograder-full-stack: deps_update_2023
- autograder-server: mutant_hints
- ag-website-vue: mutant_hints

Looking back, I don't think I've deleted (after squashing) any migrations, so jumping straight to the latest autograder-server version *should* theoretically be fine. Backing up your DB is of course recommended before doing this.

The main caveat with this would be with the versions of postgres. Have you updated away from 9.5 yet?

Sorry about the chaos, and please let me know if there's anything I can do to help!

**Comment by liamoreilly** [comment]
Hi,

Thanks for the update. I know how difficult it is to keep things all nice and neat. Communicating these things to others is then a whole other ball game.

Regarding Postgree. I saw the warning in the deployment docs. But I was not sure if this was only for new deployments (somehow) or also for existing ones. I looked at the docker-compose-single file and saw that progress there was still set to 9.5 even on the master branch. So I thought it might still be okay.

I also was unsure how to upgrade Postgres. I am not super confident with docker and Postgres. I thought it might just be changing the image number in the docker file, but I was concerned there would be some Postgres-specific things to do in the Postgres volume too. I think this needs to be documented a little more in the readmes - sorry. Is it just adjusting the image from 9.5 to 16.0 (assuming we go for the newest)? We use this a bit as a black box, so I don't really have preferences on the Postgres version.

I will try out the branches in the next day or two when I get the chance and get back to you. However, I would not like to put our live production system on these branches. I would like to keep as aligned to 'normal' as possible - even if this means delaying updates a little while (I mean they haven't been done in a while anyway).

Thanks,
Liam

Ps. There is one issue I would like to tackle. Our emails are case-insensitive in my institution (using AzureAD). But they are case-sensitive in Autograder. Thus, we have to guess on the capitalisation (when adding students to the rosters) that Student Records used when setting up the student accounts on the main system, and would you believe it, they are very inconsistent. Maybe we can look at that in due course.

**Comment by james-perretta** [comment]
So upgrading postgres is a process that requires a few steps and is not quite as simple as just bumping the version. I would definitely recommend holding off on any updates until we can get the database updated. Perhaps we can find a time for a video chat so that I can walk you through the process? 

The gist of how to update the database is to create a new postgres service and volume and dump/restore the data from the old one to the new one, so there's no risk of messing up the original data (as opposed to doing it in place). Agreed that I should definitely have some notes on that process. I've only done it once, so I've been hesitant to put official-sounding instructions out there, but I think it's time now.

As far as emails go, that should be easy enough to change. I think in practice these days emails are case insensitive. The fix I'll probably apply is having the roster page convert to lowercase before saving.

**Comment by james-perretta** [comment]
@liamoreilly I have another thought on this: It should be possible to apply the migrations incrementally by checking out each of the release branches in the autograder-server repo, rebuilding only the django image, and then applying the migrations. That way we can ensure that any dependencies between migrations are handled properly.

Happy to chat over zoom sometime and walk you through things, you can reach me at help@autograder.io.
